INSERT INTO `pw_finger_db` (`id`, `app_name`, `app_version`, `type`, `enable`, `finger`) VALUES
(3,	'joomla',	'',	'web_index_contain	',	1,	'{\"code\": 200, \"grep\":\"/media/system/js/caption.js\"}'),
(2,	'HttpFileServer',	'',	'web_index_contain',	1,	'{\"code\": 200, \"grep\": \"hfs_sid\"}'),
(1,	'mikrotik',	'',	'web_index_contain',	1,	'{\"code\": 200, \"grep\": \"mikrotik\"}'),
(265,	'AirLive_Camera',	'',	'web_header_contain',	1,	'{\'grep\':\'airlive\'}'),
(264,	'Cisco_PVC2300_Camera',	'',	'web_url_header',	1,	'{\'url\':\'/oamp/System.xml?action=login&user=L1_admin&password=L1_51\',\'code\':\'200\',\'grep\':\'sessionid\'}'),
(261,	'D-Link_DCS_Series',	'',	'web_header_contain',	1,	'{\'grep\':\'dcs-lig-httpd\'}'),
(259,	'TP-Link_Device',	'',	'web_header_contain',	1,	'{\'grep\': \'tp-link\'}'),
(260,	'IQeye_Camera',	'',	'web_header_contain',	1,	'{\'grep\':\'iqhttpd\'}'),
(258,	'RomPager_Service',	'',	'web_url_header',	1,	'{\'url\':\'/rom-0\',\'code\': 200, \'grep\': \'application/octet-stream\'}'),
(257,	'TRENDnet_webcam',	'',	'web_header_contain',	1,	'{\'grep\': \'netcam\'}'),
(254,	'NETGEAR_ReadyNAS',	'',	'web_url_contain',	1,	'{\'url\': \'/np_handler\', \'code\': 200, \'grep\': \'<payload>Empty\'}'),
(255,	'NETGEAR_DGN_Series',	'',	'web_header_contain',	1,	'{\'grep\':\'netgear dgn\'}'),
(253,	'Linksys_Device',	'',	'web_url_contain',	1,	'{\'url\': \'/HNAP1\', \'code\': 200, \'grep\': \'<VendorName>Linksys\'}'),
(252,	'airos_web',	'',	'web_header_contain',	1,	'{\'grep\':\'ubnt\'}'),
(251,	'D-Link_DIR_Series',	'',	'web_header_contain',	1,	'{\'grep\':\'dir-\'}'),
(244,	'ASUS_RT-N56U',	'',	'web_header_contain',	1,	'{\'grep\': \'rt-n56u\'}'),
(243,	'phicomm_router',	'',	'web_url_contain',	1,	'{\'url\': \'/login.asp\', \'code\': 200, \'grep\': \'400-720-5677\'}'),
(241,	'metinfo',	'',	'web_index_contain',	1,	'{\'code\': 200,\'grep\': \'metinfo.css\'}'),
(245,	'airos',	'',	'web_header_contain',	1,	'{\'grep\': \'airos\'}'),
(239,	'espcms',	'',	'web_index_contain',	1,	'{\'code\': 200,\'grep\': \'infolist_fff\'}'),
(240,	'cmseasy',	'',	'web_header_contain',	1,	'{\'grep\': \'cmseasy\'}'),
(238,	'ecshop',	'',	'web_header_contain',	1,	'{\'grep\': \'ecs_id\'}'),
(237,	'WebLogic',	'',	'web_url_contain',	1,	'{\'url\': \'/console/login/LoginForm.jsp\', \'code\': 200, \'grep\': \'WebLogic Server\'}'),
(236,	'Office Anywhere',	'',	'web_index_contain',	1,	'{\'code\': 200, \'grep\': \'/images/tongda.ico\'}'),
(235,	'ThinkPHP',	'',	'web_header_contain',	1,	'{\'grep\': \'thinkphp\'}'),
(234,	'gov_jsp_1',	'',	'web_index_contain',	0,	'{\'code\': 200, \'grep\': \'/deptWebsiteAction.do\'}'),
(222,	'tomcat',	'',	'web_url_contain',	1,	'{\'url\': \'/manager/html\', \'code\': 401, \'grep\': \'tomcat\'}'),
(223,	'phpmyadmin',	'',	'web_url_contain',	1,	'{\'url\': \'/phpmyadmin/index.php\', \'code\': 200, \'grep\': \'phpmyadmin\'}'),
(263,	'Ruijie_GateWay',	'',	'web_header_contain',	1,	'{\'grep\':\'start http-server\'}'),
(262,	'Network_Camera_LIVE_VIEW_asp',	'',	'web_url_contain',	1,	'{\'url\': \'/LIVE_VIEW.asp\', \'code\': 200, \'grep\': \'Network Camera\'}'),
(246,	'AirLink101_SkyIPCam',	'',	'web_header_contain',	1,	'{\'grep\': \'skyipcam\'}'),
(233,	'jboss',	'',	'web_header_contain',	1,	'{\'grep\': \'jboss\'}'),
(224,	'wdcp',	'',	'web_index_contain',	1,	'{\'code\': 200, \'grep\': \'wdcp\'}'),
(225,	'wordpress',	'',	'web_index_contain',	1,	'{\'code\': 200, \'grep\': \'wp-content\'}'),
(226,	'dedecms',	'',	'web_index_contain',	1,	'{\'code\': 200, \'grep\': \'/plus/search.php\'}'),
(227,	'discuz',	'',	'web_header_contain',	1,	'{\'grep\': \'_saltkey=\'}'),
(228,	'Seagate Central',	'',	'ftp_banner_contain',	1,	'{\'banner\':\'Welcome to Seagate Central Shared Storage FTP service\'}'),
(229,	'D-Link DSP-W215',	'',	'web_url_contain',	1,	'{\'url\':\'/HANP1/\',\'code\':\'200\',\'grep\':\'DSP-W215A1\'}'),
(230,	'D-Link DSP-W110',	'',	'web_url_contain',	1,	'{\'url\':\'/HANP1/\',\'code\':\'200\',\'grep\':\'DSP-W110\'}'),
(256,	'feiyuxing_router',	'',	'web_index_contain',	1,	'{\'code\': 200, \'grep\': \'R1Login.css\'}'),
(231,	'struts2',	'',	'web_index_contain',	1,	'{\'header\':\'jsessionid=\',\'code\': 200, \'grep\': \'.action\'}'),
(232,	'hikvision',	'',	'web_url_contain',	1,	'{\'url\': \'/doc/page/login.asp\', \'code\': 200, \'grep\': \'Hikvision Digital Technology\'}'),
(268,	'grandstream',	'GXV3611_HD  ',	'telnet',	0,	'{\'grep\':\'Product of Grandstream\'}'),
(4,	'h264_dvr',	'',	'web_index_contain',	0,	'{\"code\": 200, \"grep\": \"DVR Components\"}');
